services:
  reverse-proxy:
    image: traefik:v2.11
    command:
      - --api.insecure=true
      - --providers.docker
      - --entrypoints.http.address=:80
      - --entrypoints.mysql.address=:3306
      - --providers.docker.exposedbydefault=true
    ports:
      - "8090:80"
      - "8091:8080"
      - "3308:3306"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: course_catalog
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_password
    volumes:
      - ./database/volume:/var/lib/mysql
    hostname: database.cc.localhost
    labels:
      - traefik.tcp.routers.mysql.entrypoints=mysql
      - traefik.tcp.routers.mysql.rule=HostSNI(`*`)
      - traefik.tcp.services.mysql.loadbalancer.server.port=3306
    ports:
      - "8001:3306"
      - "8081:8080"
      - "3306:3306"

  api:
    image: php:8.3-apache
    container_name: api
    depends_on:
      - db
    volumes:
      - ./api/:/var/www/html/
      - ./data:/var/www/html/data/
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: >
      sh -c "
        a2enmod rewrite &&
        sed -ri -e 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/*.conf &&
        sed -ri -e 's!/var/www/!/var/www/html/public!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf &&
        docker-php-ext-install pdo pdo_mysql &&
        apache2-foreground"
    stdin_open: true
    tty: true
    hostname: api.cc.localhost
    labels:
      - traefik.http.routers.api.rule=Host(`api.cc.localhost`)

  front:
    image: php:8.3-apache
    container_name: front
    depends_on:
      - api
    volumes:
      - ./front_end/public:/var/www/html/
    stdin_open: true
    tty: true
    hostname: api.cc.localhost
    labels:
      - traefik.http.routers.front.rule=Host(`cc.localhost`)
    ports:
      - "8083:80"